//This is how Google Cloud will build our project
steps:
//Installing a firebase CLI
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase', './dockerfiles/firebase']
// npm install (Install all libraries that our project needs)
  - name: 'node:20.9'
    entrypoint: 'npm'
    args: ['install']
//npm run build (for build a project before update a firebase page)  
  - name: 'node:20.9'
    entrypoint: 'npm'
    args: ['run', 'build']
//Authenticate to Firebase with token
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args: ['use', '${_FIREBASE_PROJECT_ID}', '--token', '${_FIREBASE_TOKEN}']
//Infrom to witch Firebase hosting we want to do that deploy
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args: ['target:apply', 'hosting', 'tabletop-rpg-rule-of-coo-b1e54', 'tabletop-rpg-rule-of-coo-b1e54', '--token', '${_FIREBASE_TOKEN}']
//Firebase deploy
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args: ['deploy', '--token', '${_FIREBASE_TOKEN}', '--only', 'hosting:tabletop-rpg-rule-of-coo-b1e54']
timeout: 1200s